version: '3.2'

services:
  connect:
    image: connect
    build:
      context: ..
      args:
        VITE_COMMA_URL_ROOT: ${VITE_COMMA_URL_ROOT:-https://openpilot.copirobo.com/}
        VITE_ATHENA_URL_ROOT: ${VITE_ATHENA_URL_ROOT:-https://openpilot.copirobo.com/}
        VITE_BILLING_URL_ROOT: ${VITE_BILLING_URL_ROOT:-https://openpilot.copirobo.com/}
        VITE_USERADMIN_URL_ROOT: ${VITE_USERADMIN_URL_ROOT:-https://useradmin.copirobo.com/}
        VITE_SENTRY_ENV: ${VITE_SENTRY_ENV:-}
    ports:
      - "80:80"
