name: test

on:
  push:
    branches:
      - PonPilot
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Run unit tests
        run: bun run test
